#!/usr/bin/env python3
"""Write an SFZ mapping for a folder of raw multisamples whose names give the note and velocity layer.

Usage: samples2sfz.py SAMPLES_DIR OUTPUT.sfz --pattern REGEX [--octave-offset N] [--layers 1,3,4] [--release S]

REGEX must capture `note` (C, C#, Db…), `octave` and `vel` (layer number, 1 = softest); an optional `rr` group
keeps round-robin 1 only. Example (VCSL): '_(?P<note>[A-G]#?)(?P<octave>-?\\d)_vl?(?P<vel>\\d)_rr(?P<rr>\\d)'.
--octave-offset: MIDI octave of name octave 0 (VCSL names the piano's lowest A « A-1 »: C3 = 60, offset 2).
--layers: velocity layers to keep, to fit a bank in memory (default: all). Kept layers share 1-127 evenly.

--layer-spread DB: level gap between the loudest and the softest kept layer. Raw multisamples keep the piano's real
dynamics (pp 35-40 dB under ff); on top of the sampler's own velocity curve, soft playing would be inaudible live.
--gain DB: boost for every layer (quiet recordings, peaks well under 0 dBFS), on top of --layer-spread.
Each layer too soft for an even step between 0 and -DB gets a `volume` boost; none is made quieter.

Each sample covers the keys up to halfway to its neighbours; a note missing a layer borrows its nearest one.
Then convert with scripts/sfz2sf2.py.
"""
import argparse
import math
import os
import re
import statistics
import struct
import subprocess
import tempfile
import wave

SEMITONES = {'C': 0, 'C#': 1, 'DB': 1, 'D': 2, 'D#': 3, 'EB': 3, 'E': 4, 'F': 5, 'F#': 6, 'GB': 6, 'G': 7,
             'G#': 8, 'AB': 8, 'A': 9, 'A#': 10, 'BB': 10, 'B': 11}


def peak_db(path: str) -> float:
    """Peak of a sample in dBFS, decoded with macOS afconvert."""
    with tempfile.TemporaryDirectory() as tmp:
        out = os.path.join(tmp, 'peak.wav')
        subprocess.run(['afconvert', '-f', 'WAVE', '-d', 'LEI16', path, out], check=True)
        with wave.open(out) as w:
            frames = w.readframes(w.getnframes())
    peak = max((abs(v) for v in struct.unpack(f'<{len(frames) // 2}h', frames)), default=0)
    return 20 * math.log10(max(peak, 1) / 32768)


def main():
    p = argparse.ArgumentParser()
    p.add_argument('samples')
    p.add_argument('output')
    p.add_argument('--pattern', required=True)
    p.add_argument('--octave-offset', type=int, default=1)
    p.add_argument('--layers')
    p.add_argument('--release', type=float, default=0.4)
    p.add_argument('--layer-spread', type=float)
    p.add_argument('--gain', type=float, default=0.0)
    args = p.parse_args()

    pattern = re.compile(args.pattern)
    samples = {}  # (key, layer) -> file
    for name in sorted(os.listdir(args.samples)):
        m = pattern.search(name)
        if not m or not name.lower().endswith(('.wav', '.flac')):
            continue
        if 'rr' in m.groupdict() and m.group('rr') not in (None, '1'):
            continue
        key = (int(m.group('octave')) + args.octave_offset) * 12 + SEMITONES[m.group('note').upper()]
        samples[(key, int(m.group('vel')))] = name
    if not samples:
        raise SystemExit('no sample matches the pattern')

    keys = sorted({k for k, _ in samples})
    layers = sorted({v for _, v in samples})
    if args.layers:
        layers = [int(v) for v in args.layers.split(',')]

    gains = {layer: 0.0 for layer in layers}
    if args.layer_spread is not None and len(layers) > 1:
        peaks = {v: statistics.median(peak_db(os.path.join(args.samples, f)) for (_, l), f in samples.items() if l == v)
                 for v in layers}
        loudest = peaks[layers[-1]]
        for j, layer in enumerate(layers):
            target = loudest - args.layer_spread * (len(layers) - 1 - j) / (len(layers) - 1)
            # Only lift layers that are too soft: a recording with a narrower range than DB stays as is.
            gains[layer] = max(round(target - peaks[layer], 1), 0.0)
        print('layer peaks (dBFS):', {v: round(peaks[v], 1) for v in layers}, '-> volume', gains)
    gains = {layer: round(gain + args.gain, 1) for layer, gain in gains.items()}

    lines = [f'// Generated by scripts/samples2sfz.py from {os.path.basename(os.path.normpath(args.samples))}',
             '<control>', f'default_path={os.path.relpath(args.samples, os.path.dirname(os.path.abspath(args.output)))}/',
             '<global>', 'ampeg_attack=0.001', f'ampeg_release={args.release}', '']
    for i, key in enumerate(keys):
        lo = 0 if i == 0 else (keys[i - 1] + key) // 2 + 1
        hi = 127 if i == len(keys) - 1 else (key + keys[i + 1]) // 2
        available = sorted(v for k, v in samples if k == key)
        for j, layer in enumerate(layers):
            # Nearest recorded layer when this note lacks one (the softest notes are sometimes missing).
            source = min(available, key=lambda v: (abs(v - layer), v))
            lovel = 1 + (127 * j) // len(layers)
            hivel = (127 * (j + 1)) // len(layers)
            volume = f' volume={gains[source]}' if gains.get(source) else ''
            lines.append(f'<region> sample={samples[(key, source)]} lokey={lo} hikey={hi} '
                         f'pitch_keycenter={key} lovel={lovel} hivel={hivel}{volume}')
    with open(args.output, 'w') as f:
        f.write('\n'.join(lines) + '\n')
    print(f'{args.output}: {len(keys)} notes ({keys[0]}-{keys[-1]}), layers {layers}, {len(lines) - 7} regions')


if __name__ == '__main__':
    main()
